site_name: Jessen ruokarähinä
site_url: https://ravinto.ptjesse.fi
theme:
  name: material
  language: fi
  custom_dir: overrides
  features:
  #   - header.autohide
    - navigation.top
  logo: ./assets/Jesse-Raitapuro-favicon.png
  favicon: ./assets/Jesse-Raitapuro-favicon.png
  font: false

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: green
      toggle:
        icon: material/brightness-4
        name: Vaihda tummaan tilaan

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Vaihda vaaleaan tilaan

  features:
    - search.share

# extra_javascript:
#   - javascripts/cookie-banner.js
  # - javascripts/cookie-config.js


copyright:   Copyright &copy; 2022 Jesse Raitapuro

extra_css:
  # - stylesheets/cookie-banner.css
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes

  

extra:
  generator: false
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/jesse_raitapuro

plugins:
  - search:
      lang: fi